SELECT DISTINCT(CITY), LENGTH(CITY) AS L FROM STATION
WHERE LENGTH(CITY) IN ( SELECT MIN(LENGTH(CITY)) FROM STATION)
ORDER BY CITY
LIMIT 1;
            
                                  
SELECT DISTINCT(CITY), LENGTH(CITY) AS L FROM STATION
WHERE LENGTH(CITY) IN (SELECT MAX(LENGTH(CITY)) FROM STATION)
ORDER BY CITY desc
LIMIT 1;
